from Wektor import Vector

x = Vector()
print("Początkowe współrzędne x: ", x)
x.los()
print("Współrzędne x wygenerowane losowo: ", x)
y = Vector()
print("Początkowe współrzędne y: ", y)
y.los()
print("Współrzędne y wygenerowane losowo: ", y)
print("Suma wektorów: ", x+y)
print("Odejmowanie x i y: ", x-y)
print("Wektor x pomnożony przez 4: ", x.mnozenie_przez_skalar(4))
print("Długość wektora x: ", x.dlugosc_wektora())
print("Wartość iloczynu skalarnego x i y: ", x*y)
print("Suma współrzędnych x: ", x.suma_elementow())
print("Sprawdź, czy 4 jest wśród współrzędnych x: ", 4 in x)
print("Sprawdź, jaka współrzędna jest na pozycji [1]: ", x[1])
print("Zmiana współrzędnych x: ", x.elementy_wektora([0, 3, 2]))
